CREATE TABLE dbo.Users(
	Id INT PRIMARY KEY IDENTITY(1,1),
	FirstName VARCHAR(50) NOT NULL, 
	LastName VARCHAR(50) NULL, 
	Email VARCHAR(200) NOT NULL, 
	PhoneNumber VARCHAR(20) NULL, 
	Salt VARCHAR(50) NOT NULL, 
	UserPassword VARCHAR(500) NOT NULL,
	DateCreated DATETIME NOT NULL DEFAULT GETDATE(),
	SessionKey VARCHAR(50) NULL
)
