//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qup.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class SessionLog
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string IpAddress { get; set; }
        public string ServerName { get; set; }
        public string SessionKey { get; set; }
        public string XForwardedFor { get; set; }
        public string Browser { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual User User { get; set; }
    }
}
