//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qup.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwUserPagePermission
    {
        public int Id { get; set; }
        public string Url { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> UserGroupId { get; set; }
        public Nullable<int> PageId { get; set; }
    }
}
